MUI theme.js created
Chat-Your-Way/chatyourway-ui pull request #2
Opened 2023-07-27 16:49 UTC by IlliaKomissarov

I've got to know the MUI, I'm still dealing with the documentation, so far I've added only the colors from the layout to the theme, more to come

2023-07-28 06:39 UTC, mykhalenych requested changes

2023-07-28 06:39 UTC, mykhalenych commented on src/App.js
> +import theme from "./theme/theme";
keep import order

2023-07-28 06:39 UTC, mykhalenych commented on src/App.js
> +      <Typography variant="h1" sx={{ color: theme.palette.primary.main }}>
```suggestion
      <Typography variant="h1">
```

2023-07-28 06:39 UTC, mykhalenych commented on src/theme/theme.js
> +const theme = createTheme({
```suggestion
const createCommonTheme = (theme) => createTheme({
```

2023-07-28 06:39 UTC, mykhalenych commented on src/theme/theme.js
> +
```suggestion

const lightPalette = createTheme({
    palette: {
        primary: {
            light: '',
            main: '',
            dark: '',
            contrastText: '',
        },
    });

```

2023-07-28 06:39 UTC, mykhalenych commented on src/theme/theme.js
> +    primary: {
move colors to lightPalette

2023-07-28 06:39 UTC, mykhalenych commented on src/theme/theme.js
> +  palette: {
```suggestion
  ...theme,
      components: {
        MuiTypography: {
           styleOverrides: {
                root: {
                   fontFamily: 'Inter, sans-serif',
                   color: theme.palette.primary.main,
               }
           },
       },
   },
```

2023-07-28 06:39 UTC, mykhalenych commented on src/theme/theme.js
> +export default theme;
```suggestion
const lightTheme = createTheme(createCommonTheme(lightPalette));
```

2023-07-28 06:39 UTC, mykhalenych commented on src/App.js
> +    <ThemeProvider theme={theme}>
```suggestion
    <ThemeProvider theme={lightTheme}>
```

2023-07-28 06:47 UTC, mykhalenych requested changes
<img width="163" alt="Screenshot 2023-07-28 at 09 47 31" src="https://github.com/Chat-Your-Way/chatyourway-ui/assets/53228259/c70b9990-d4af-4345-8fdf-bf875317d083">
rename App.js => App.jsx

2023-07-28 16:40 UTC, Irina-M-lu commented
Trying to play with your code after just copied it; works fine. 
I managed to add buttons and checkboxes to App.jsx, but we need them as separate components, right? In this case, where should we add their styles - to a component itself or to the theme.js file? 
Простою мовою: де ми прописуємо основні стилі компонентів (наприклад, кнопка) - в одному загальному файлі theme.js, у самому компоненті або до кожного компонента потрібен свій theme.js?
@mykhalenych  ?

2023-07-28 17:35 UTC, IlliaKomissarov commented
> Trying to play with your code after just copied it; works fine. I managed to add buttons and checkboxes to App.jsx, but we need them as separate components, right? In this case, where should we add their styles - to a component itself or to the theme.js file? Простою мовою: де ми прописуємо основні стилі компонентів (наприклад, кнопка) - в одному загальному файлі theme.js, у самому компоненті або до кожного компонента потрібен свій theme.js? @mykhalenych ?

To do this, we simply create a file in the component folder, for example, button-styled.js, and use the styled component there, which we then export to our component.

2023-07-28 17:47 UTC, Irina-M-lu commented
> > Trying to play with your code after just copied it; works fine. I managed to add buttons and checkboxes to App.jsx, but we need them as separate components, right? In this case, where should we add their styles - to a component itself or to the theme.js file? Простою мовою: де ми прописуємо основні стилі компонентів (наприклад, кнопка) - в одному загальному файлі theme.js, у самому компоненті або до кожного компонента потрібен свій theme.js? @mykhalenych ?
> 
> To do this, we simply create a file in the component folder, for example, button-styled.js, and use the styled component there, which we then export to our component.

То есть:
component folder 
     Component.jsx (import component-styled.js )
     component-styled.js 
           import { createTheme } ...
          const createComponentStyled = {...}
App.jsx 
       import Component from './Component'
 Так?
Или просто стилизуем компонент внутри Component.jsx?

2023-07-29 09:58 UTC, IlliaKomissarov commented
> > > Trying to play with your code after just copied it; works fine. I managed to add buttons and checkboxes to App.jsx, but we need them as separate components, right? In this case, where should we add their styles - to a component itself or to the theme.js file? Простою мовою: де ми прописуємо основні стилі компонентів (наприклад, кнопка) - в одному загальному файлі theme.js, у самому компоненті або до кожного компонента потрібен свій theme.js? @mykhalenych ?
> > 
> > 
> > To do this, we simply create a file in the component folder, for example, button-styled.js, and use the styled component there, which we then export to our component.
> 
> То есть: component folder -> Component.jsx (import component-styled.js ) -> component-styled.js import { createTheme } ... const createComponentStyled = {...} App.jsx -> import Component from './Component' Так? Или просто стилизуем компонент внутри Component.jsx?

That's right.

2023-08-03 09:15 UTC, mykhalenych approved these changes

2023-08-04 06:26 UTC, merged