Chat 82 faq page
Chat-Your-Way/chatyourway-ui pull request #30
Opened 2023-10-09 20:35 UTC by KyrychenkoDmytro

2023-10-11 13:54 UTC, DStukalo requested changes
Accordeon don't change icon when he open. Accordeon icons don't change color in dark theme.

2023-11-09 15:18 UTC, Skynet4241 approved these changes

2023-11-09 15:18 UTC, Skynet4241 commented on src/components/Layouts/Header/Header.jsx
Remove changes from Heder

2023-11-09 15:18 UTC, Skynet4241 commented on src/App.jsx
> +            <Route path="/faq" element={<FaqPage />} />
Delete it

2023-11-09 15:18 UTC, Skynet4241 commented on src/components/ExpandIcon/ExpandIcon.jsx
> +      sx={{
Delete the styles here and move them to file ExpandIcon.styled.js

2023-11-09 15:18 UTC, Skynet4241 commented on src/components/ExpandIcon/ExpandIcon.jsx
> +      <div className="expandIconWrapper">
Use Box from Material-UI / we write all styles through styled-components

2023-11-09 15:18 UTC, Skynet4241 commented on src/components/ExpandIcon/ExpandIcon.jsx
> +      <div className="collapsIconWrapper">
And here too

2023-11-09 15:18 UTC, Skynet4241 commented on src/pages/FaqPage/FaqPage.jsx
> +          // sx={{
Delete it

2023-11-09 15:18 UTC, Skynet4241 commented on src/ui-kit/theme/theme.js
> +            whiteRBGA: '#FFFFFF',
What is this for?

2023-11-09 15:18 UTC, Skynet4241 commented on src/ui-kit/theme/theme.js
> +            darkPurple: 'FFFFFF',
What is this for?

2023-11-09 15:18 UTC, Skynet4241 commented on src/pages/FaqPage/FaqPage.jsx
> +      <FaqPageTitle variant="h21">The most common questions</FaqPageTitle>
Does not match the.

2023-11-09 15:18 UTC, Skynet4241 commented on src/pages/FaqPage/FaqPage.jsx
> +            {title}
The color does not match the layout

2023-11-09 15:18 UTC, Skynet4241 commented on src/ui-kit/theme/theme.js
> +            lightPurple: '6261AF',
What is this for? Should be preceded by #

2023-11-09 15:18 UTC, Skynet4241 commented on src/ui-kit/theme/theme.js
> +            lightPurple: 'EEEFFF',
What is this for? Should be preceded by #

2023-11-23 18:08 UTC, DStukalo approved these changes

2023-11-23 18:12 UTC, merged