Chat 35 component input
Chat-Your-Way/chatyourway-ui pull request #9
Opened 2023-08-31 19:39 UTC by miamarichka

fixes comments from previous commit

2023-09-01 07:03 UTC, FortizFil requested changes

2023-09-01 07:03 UTC, FortizFil commented on src/ui-kit/components/Input/EmailInput/EmailInput.jsx
> +  const handleInputChange = (e) => {
This function is not working correctly.

2023-09-01 07:03 UTC, FortizFil commented on src/ui-kit/components/Input/PasswordInput/PasswordInput.jsx
> +  const handleInputChange = (e) => {
This function is not working correctly.

2023-09-02 13:01 UTC, miamarichka commented on src/ui-kit/components/Input/EmailInput/EmailInput.jsx
> +      <EmailInputStyled
I added but for not its value totally undercontrol and  its empty string for now

2023-09-02 13:02 UTC, miamarichka commented on src/ui-kit/components/Input/PasswordInput/PasswordInput.jsx
> +      <PasswordInputStyled
same here

2023-09-02 13:02 UTC, miamarichka commented on src/ui-kit/components/Input/SearchInput/SearchInput.jsx
> +    <SearchInputStyled
here I did some small validation on empty string with key up and passed a fucntion like a prop to handle the received value

2023-09-02 13:03 UTC, miamarichka commented on src/ui-kit/components/Input/EmailInput/EmailInput.jsx
> +        sx={{
done

2023-09-02 13:03 UTC, miamarichka commented on src/ui-kit/components/Input/PasswordInput/PasswordInput.jsx
> +        sx={{
done

2023-09-02 13:04 UTC, miamarichka commented on src/ui-kit/components/Input/PasswordInput/PasswordInput.jsx
> +              sx={{
but here it styles totally depends on input value, its changes dynamic

2023-09-04 06:51 UTC, FortizFil requested changes

2023-09-04 06:51 UTC, FortizFil commented on src/ui-kit/components/Input/PasswordInput/PasswordInput.jsx
> +              sx={{
It can be done as I say

2023-09-04 06:51 UTC, FortizFil commented on src/ui-kit/components/Input/PasswordInput/PasswordInput.jsx
> +        sx={{
Not all

2023-09-04 06:51 UTC, FortizFil commented on src/ui-kit/components/Input/EmailInput/EmailInput.jsx
> +        sx={{
Not all

2023-09-04 06:51 UTC, FortizFil commented on src/ui-kit/components/Input/SearchInput/SearchInput.jsx
> +    <SearchInputStyled
function accepts value and onChange, remove all unnecessary

2023-09-04 06:51 UTC, FortizFil commented on src/ui-kit/components/Input/EmailInput/EmailInput.jsx
> +const EmailInput = ({
Add an explicit onChange prop

2023-09-04 06:51 UTC, FortizFil commented on src/ui-kit/components/Input/PasswordInput/PasswordInput.jsx
> +  placeholderText = 'Minimum of 8 characters',
Add an explicit onChange prop

2023-09-04 13:46 UTC, FortizFil approved these changes

2023-09-07 08:25 UTC, merged